"use client";

import { useMemo } from "react";

export default function useLiveMapState({
  showVehiclesLayer,
  shouldHideVehicleVisualLayers,
  shouldClusterVehicles,
  clusteredVehiclesToShow,
  handleVehicleSelect,
  handleClusterHover,
  handleClusterLeave,
  disableClusterSpiderfy,
  clusterRadiusPx,
  movingVehiclesToShow,
  selectedVehicleId,
  bubbleAnimatedVehicleIds,
  showVehicleLabels,
  shouldShowGlobalVehicleLabels,
  selectedVehiclePlaybackActive,
  getVehicleMarkerRef,
  previousVehicleStates,
  handlePlaybackMenuFromPopup,
  onTelemetryOpen,
  isMobileViewport,
  selectedCenter,
  isSelectedVehicleClustered,
}) {
  return useMemo(
    () => ({
      showVehiclesLayer,
      shouldHideVehicleVisualLayers,
      shouldClusterVehicles,
      clusteredVehiclesToShow,
      handleVehicleSelect,
      handleClusterHover,
      handleClusterLeave,
      disableClusterSpiderfy,
      clusterRadiusPx,
      movingVehiclesToShow,
      selectedVehicleId,
      bubbleAnimatedVehicleIds,
      showVehicleLabels,
      shouldShowGlobalVehicleLabels,
      selectedVehiclePlaybackActive,
      getVehicleMarkerRef,
      previousVehicleStates,
      handlePlaybackMenuFromPopup,
      onTelemetryOpen,
      isMobileViewport,
      selectedCenter,
      isSelectedVehicleClustered,
    }),
    [
      bubbleAnimatedVehicleIds,
      clusterRadiusPx,
      clusteredVehiclesToShow,
      disableClusterSpiderfy,
      getVehicleMarkerRef,
      handleClusterHover,
      handleClusterLeave,
      handlePlaybackMenuFromPopup,
      handleVehicleSelect,
      isSelectedVehicleClustered,
      movingVehiclesToShow,
      onTelemetryOpen,
      previousVehicleStates,
      selectedCenter,
      selectedVehicleId,
      selectedVehiclePlaybackActive,
      isMobileViewport,
      shouldClusterVehicles,
      shouldHideVehicleVisualLayers,
      shouldShowGlobalVehicleLabels,
      showVehicleLabels,
      showVehiclesLayer,
    ]
  );
}
